### PR TITLE
3 thousand lines of translation.... WHERE SO MUCH?)

### PR DESCRIPTION
**Pull request by bropines**
I tried to fully translate all the functions. I think it turned out fine

### CODE REVIEW

**Comment by xuejianxianzun** [comment]
Thank you, I will test it tomorrow.

**Comment by xuejianxianzun** [comment]
In the language switch, can I display "Russian" as "ру́сский язы́к"?

**Comment by bropines** [comment]
"Or only "ру́сский"?"

I think that should be enough.

**Comment by xuejianxianzun** [comment]
The following text has no Russian translation:

```
_wiki
_用户id
_当前状态
_已下载
_举报
_id范围
_大于
_小于
_命名
_无损
_完成
_自动检测
_待处理
_全年龄
_收藏
_尺寸
_增强
_等待时间
_赞助我
_上限
_分钟
```

**Pull request merged**
